[package]
name = "cppteach"
version = "0.1.2"
description = "RunCode IDE"
authors = ["YuanMing"]
edition = "2021"

[lib]
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "devtools"] }
tauri-plugin-dialog = "2"
tauri-plugin-decoration = "2.1.4"
portable-pty = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", default-features = false }
tempfile = "3"
which = "6"
uuid = { version = "1", features = ["v4"] }
thiserror = "1"
libc = "0.2"
zip = { version = "2", default-features = false, features = ["deflate"] }
walkdir = "2"
tree-sitter = "0.22"
tree-sitter-cpp = "0.22"

# Windows 平台依赖（JobObject + GetProcessMemoryInfo）
[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_JobObjects",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

