// C++ 关键词 + STL 补全数据源（纯文本补全，无 snippet 占位符）
// kind 用字符串别名，在 Editor.tsx 中映射为 monaco.languages.CompletionItemKind

export type KeywordKind =
  | "Keyword"
  | "Class"
  | "Function"
  | "Variable"
  | "Constant"
  | "Module";

export interface KeywordDef {
  label: string;
  kind: KeywordKind;
  detail: string;
}

// C++ 关键词
const CPP_KEYWORDS: KeywordDef[] = [
  { label: "int", kind: "Keyword", detail: "C++ 关键词" },
  { label: "long", kind: "Keyword", detail: "C++ 关键词" },
  { label: "double", kind: "Keyword", detail: "C++ 关键词" },
  { label: "float", kind: "Keyword", detail: "C++ 关键词" },
  { label: "char", kind: "Keyword", detail: "C++ 关键词" },
  { label: "bool", kind: "Keyword", detail: "C++ 关键词" },
  { label: "void", kind: "Keyword", detail: "C++ 关键词" },
  { label: "short", kind: "Keyword", detail: "C++ 关键词" },
  { label: "unsigned", kind: "Keyword", detail: "C++ 关键词" },
  { label: "signed", kind: "Keyword", detail: "C++ 关键词" },
  { label: "const", kind: "Keyword", detail: "C++ 关键词" },
  { label: "static", kind: "Keyword", detail: "C++ 关键词" },
  { label: "constexpr", kind: "Keyword", detail: "C++ 关键词" },
  { label: "inline", kind: "Keyword", detail: "C++ 关键词" },
  { label: "virtual", kind: "Keyword", detail: "C++ 关键词" },
  { label: "explicit", kind: "Keyword", detail: "C++ 关键词" },
  { label: "friend", kind: "Keyword", detail: "C++ 关键词" },
  { label: "mutable", kind: "Keyword", detail: "C++ 关键词" },
  { label: "volatile", kind: "Keyword", detail: "C++ 关键词" },
  { label: "register", kind: "Keyword", detail: "C++ 关键词" },
  { label: "extern", kind: "Keyword", detail: "C++ 关键词" },
  { label: "auto", kind: "Keyword", detail: "C++ 关键词" },
  { label: "nullptr", kind: "Keyword", detail: "C++ 关键词" },
  { label: "true", kind: "Keyword", detail: "C++ 关键词" },
  { label: "false", kind: "Keyword", detail: "C++ 关键词" },
  { label: "struct", kind: "Keyword", detail: "C++ 关键词" },
  { label: "class", kind: "Keyword", detail: "C++ 关键词" },
  { label: "enum", kind: "Keyword", detail: "C++ 关键词" },
  { label: "union", kind: "Keyword", detail: "C++ 关键词" },
  { label: "namespace", kind: "Keyword", detail: "C++ 关键词" },
  { label: "using", kind: "Keyword", detail: "C++ 关键词" },
  { label: "template", kind: "Keyword", detail: "C++ 关键词" },
  { label: "typename", kind: "Keyword", detail: "C++ 关键词" },
  { label: "typedef", kind: "Keyword", detail: "C++ 关键词" },
  { label: "if", kind: "Keyword", detail: "C++ 关键词" },
  { label: "else", kind: "Keyword", detail: "C++ 关键词" },
  { label: "for", kind: "Keyword", detail: "C++ 关键词" },
  { label: "while", kind: "Keyword", detail: "C++ 关键词" },
  { label: "do", kind: "Keyword", detail: "C++ 关键词" },
  { label: "switch", kind: "Keyword", detail: "C++ 关键词" },
  { label: "case", kind: "Keyword", detail: "C++ 关键词" },
  { label: "default", kind: "Keyword", detail: "C++ 关键词" },
  { label: "break", kind: "Keyword", detail: "C++ 关键词" },
  { label: "continue", kind: "Keyword", detail: "C++ 关键词" },
  { label: "return", kind: "Keyword", detail: "C++ 关键词" },
  { label: "goto", kind: "Keyword", detail: "C++ 关键词" },
  { label: "sizeof", kind: "Keyword", detail: "C++ 关键词" },
  { label: "new", kind: "Keyword", detail: "C++ 关键词" },
  { label: "delete", kind: "Keyword", detail: "C++ 关键词" },
  { label: "this", kind: "Keyword", detail: "C++ 关键词" },
  { label: "public", kind: "Keyword", detail: "C++ 访问修饰符" },
  { label: "protected", kind: "Keyword", detail: "C++ 访问修饰符" },
  { label: "private", kind: "Keyword", detail: "C++ 访问修饰符" },
  { label: "override", kind: "Keyword", detail: "C++ 关键词" },
  { label: "final", kind: "Keyword", detail: "C++ 关键词" },
  { label: "operator", kind: "Keyword", detail: "C++ 关键词" },
  { label: "try", kind: "Keyword", detail: "C++ 关键词" },
  { label: "catch", kind: "Keyword", detail: "C++ 关键词" },
  { label: "throw", kind: "Keyword", detail: "C++ 关键词" },
  { label: "noexcept", kind: "Keyword", detail: "C++ 关键词" },
];

// STL 容器
const STL_CONTAINERS: KeywordDef[] = [
  { label: "vector", kind: "Class", detail: "STL 容器" },
  { label: "map", kind: "Class", detail: "STL 容器" },
  { label: "unordered_map", kind: "Class", detail: "STL 容器" },
  { label: "set", kind: "Class", detail: "STL 容器" },
  { label: "unordered_set", kind: "Class", detail: "STL 容器" },
  { label: "multiset", kind: "Class", detail: "STL 容器" },
  { label: "multimap", kind: "Class", detail: "STL 容器" },
  { label: "unordered_multiset", kind: "Class", detail: "STL 容器" },
  { label: "unordered_multimap", kind: "Class", detail: "STL 容器" },
  { label: "queue", kind: "Class", detail: "STL 容器" },
  { label: "deque", kind: "Class", detail: "STL 容器" },
  { label: "priority_queue", kind: "Class", detail: "STL 容器" },
  { label: "stack", kind: "Class", detail: "STL 容器" },
  { label: "string", kind: "Class", detail: "STL 容器" },
  { label: "pair", kind: "Class", detail: "STL 类型" },
  { label: "tuple", kind: "Class", detail: "STL 类型" },
  { label: "array", kind: "Class", detail: "STL 容器" },
  { label: "list", kind: "Class", detail: "STL 容器" },
  { label: "forward_list", kind: "Class", detail: "STL 容器" },
  { label: "bitset", kind: "Class", detail: "STL 类型" },
];

// STL 算法
const STL_ALGORITHMS: KeywordDef[] = [
  { label: "sort", kind: "Function", detail: "STL 算法" },
  { label: "stable_sort", kind: "Function", detail: "STL 算法" },
  { label: "partial_sort", kind: "Function", detail: "STL 算法" },
  { label: "nth_element", kind: "Function", detail: "STL 算法" },
  { label: "lower_bound", kind: "Function", detail: "STL 算法" },
  { label: "upper_bound", kind: "Function", detail: "STL 算法" },
  { label: "binary_search", kind: "Function", detail: "STL 算法" },
  { label: "unique", kind: "Function", detail: "STL 算法" },
  { label: "reverse", kind: "Function", detail: "STL 算法" },
  { label: "rotate", kind: "Function", detail: "STL 算法" },
  { label: "next_permutation", kind: "Function", detail: "STL 算法" },
  { label: "prev_permutation", kind: "Function", detail: "STL 算法" },
  { label: "max", kind: "Function", detail: "STL 算法" },
  { label: "min", kind: "Function", detail: "STL 算法" },
  { label: "max_element", kind: "Function", detail: "STL 算法" },
  { label: "min_element", kind: "Function", detail: "STL 算法" },
  { label: "abs", kind: "Function", detail: "STL 算法" },
  { label: "swap", kind: "Function", detail: "STL 算法" },
  { label: "fill", kind: "Function", detail: "STL 算法" },
  { label: "accumulate", kind: "Function", detail: "STL 算法" },
  { label: "count", kind: "Function", detail: "STL 算法" },
  { label: "find", kind: "Function", detail: "STL 算法" },
  { label: "find_if", kind: "Function", detail: "STL 算法" },
  { label: "for_each", kind: "Function", detail: "STL 算法" },
  { label: "copy", kind: "Function", detail: "STL 算法" },
  { label: "remove", kind: "Function", detail: "STL 算法" },
  { label: "begin", kind: "Function", detail: "STL 迭代器" },
  { label: "end", kind: "Function", detail: "STL 迭代器" },
  { label: "rbegin", kind: "Function", detail: "STL 迭代器" },
  { label: "rend", kind: "Function", detail: "STL 迭代器" },
  { label: "size", kind: "Function", detail: "STL 工具" },
  { label: "empty", kind: "Function", detail: "STL 工具" },
  { label: "front", kind: "Function", detail: "STL 工具" },
  { label: "back", kind: "Function", detail: "STL 工具" },
  { label: "push_back", kind: "Function", detail: "STL 方法" },
  { label: "emplace_back", kind: "Function", detail: "STL 方法" },
  { label: "pop_back", kind: "Function", detail: "STL 方法" },
  { label: "push", kind: "Function", detail: "STL 方法" },
  { label: "pop", kind: "Function", detail: "STL 方法" },
  { label: "top", kind: "Function", detail: "STL 方法" },
  { label: "insert", kind: "Function", detail: "STL 方法" },
  { label: "erase", kind: "Function", detail: "STL 方法" },
  { label: "clear", kind: "Function", detail: "STL 方法" },
  { label: "resize", kind: "Function", detail: "STL 方法" },
  { label: "reserve", kind: "Function", detail: "STL 方法" },
  { label: "at", kind: "Function", detail: "STL 方法" },
  { label: "substr", kind: "Function", detail: "string 方法" },
  { label: "c_str", kind: "Function", detail: "string 方法" },
  { label: "length", kind: "Function", detail: "string 方法" },
  { label: "to_string", kind: "Function", detail: "STL 工具" },
  { label: "stoi", kind: "Function", detail: "STL 工具" },
  { label: "make_pair", kind: "Function", detail: "STL 工具" },
  { label: "make_tuple", kind: "Function", detail: "STL 工具" },
  { label: "tie", kind: "Function", detail: "STL 工具" },
];

// 常用类型与 IO
const CPP_IO_TYPES: KeywordDef[] = [
  { label: "size_t", kind: "Class", detail: "标准类型" },
  { label: "int64_t", kind: "Class", detail: "标准类型" },
  { label: "int32_t", kind: "Class", detail: "标准类型" },
  { label: "uint64_t", kind: "Class", detail: "标准类型" },
  { label: "uint32_t", kind: "Class", detail: "标准类型" },
  { label: "printf", kind: "Function", detail: "C 标准 IO" },
  { label: "scanf", kind: "Function", detail: "C 标准 IO" },
  { label: "puts", kind: "Function", detail: "C 标准 IO" },
  { label: "getchar", kind: "Function", detail: "C 标准 IO" },
  { label: "putchar", kind: "Function", detail: "C 标准 IO" },
  { label: "cin", kind: "Variable", detail: "C++ 标准流" },
  { label: "cout", kind: "Variable", detail: "C++ 标准流" },
  { label: "cerr", kind: "Variable", detail: "C++ 标准流" },
  { label: "clog", kind: "Variable", detail: "C++ 标准流" },
  { label: "endl", kind: "Constant", detail: "C++ IO 操纵符" },
  { label: "flush", kind: "Constant", detail: "C++ IO 操纵符" },
  { label: "fixed", kind: "Constant", detail: "C++ IO 操纵符" },
  { label: "setprecision", kind: "Function", detail: "C++ IO 操纵符" },
  { label: "setw", kind: "Function", detail: "C++ IO 操纵符" },
  { label: "freopen", kind: "Function", detail: "C 标准库" },
  { label: "malloc", kind: "Function", detail: "C 标准库" },
  { label: "free", kind: "Function", detail: "C 标准库" },
  { label: "exit", kind: "Function", detail: "C 标准库" },
  { label: "assert", kind: "Function", detail: "C 标准库" },
];

// 常用宏与预处理
const CPP_PREPROCESSOR: KeywordDef[] = [
  { label: "include", kind: "Keyword", detail: "预处理指令" },
  { label: "define", kind: "Keyword", detail: "预处理指令" },
  { label: "ifdef", kind: "Keyword", detail: "预处理指令" },
  { label: "ifndef", kind: "Keyword", detail: "预处理指令" },
  { label: "endif", kind: "Keyword", detail: "预处理指令" },
  { label: "pragma", kind: "Keyword", detail: "预处理指令" },
];

// OI 常用头文件（与容器名冲突的不重复加：string/vector/map/set/queue/deque/list/array/bitset）
const CPP_HEADERS: KeywordDef[] = [
  { label: "bits/stdc++.h", kind: "Module", detail: "OI 万能头" },
  { label: "iostream", kind: "Module", detail: "C++ 头文件" },
  { label: "cstdio", kind: "Module", detail: "C 头文件" },
  { label: "cstring", kind: "Module", detail: "C 头文件" },
  { label: "cmath", kind: "Module", detail: "C 头文件" },
  { label: "cstdlib", kind: "Module", detail: "C 头文件" },
  { label: "climits", kind: "Module", detail: "C 头文件" },
  { label: "cstdint", kind: "Module", detail: "C++ 头文件" },
  { label: "numeric", kind: "Module", detail: "C++ 头文件" },
  { label: "functional", kind: "Module", detail: "C++ 头文件" },
  { label: "utility", kind: "Module", detail: "C++ 头文件" },
  { label: "cassert", kind: "Module", detail: "C 头文件" },
  { label: "ctime", kind: "Module", detail: "C 头文件" },
  { label: "random", kind: "Module", detail: "C++ 头文件" },
  { label: "algorithm", kind: "Module", detail: "C++ 头文件" },
];

// OI 常用算法扩展（数学 + 内存 + 排列等）
const OI_ALGORITHMS_EXT: KeywordDef[] = [
  { label: "iota", kind: "Function", detail: "STL 算法（numeric）" },
  { label: "partial_sum", kind: "Function", detail: "STL 算法（numeric）" },
  { label: "inplace_merge", kind: "Function", detail: "STL 算法" },
  { label: "shuffle", kind: "Function", detail: "STL 算法（C++11）" },
  { label: "gcd", kind: "Function", detail: "C++17 std::gcd" },
  { label: "lcm", kind: "Function", detail: "C++17 std::lcm" },
  { label: "__gcd", kind: "Function", detail: "GCC 内置 gcd" },
  { label: "__lg", kind: "Function", detail: "GCC 内置 log2" },
  { label: "memset", kind: "Function", detail: "C 内存库（cstring）" },
  { label: "memcpy", kind: "Function", detail: "C 内存库（cstring）" },
  { label: "sqrt", kind: "Function", detail: "cmath 数学函数" },
  { label: "pow", kind: "Function", detail: "cmath 数学函数" },
  { label: "ceil", kind: "Function", detail: "cmath 数学函数" },
  { label: "floor", kind: "Function", detail: "cmath 数学函数" },
  { label: "log", kind: "Function", detail: "cmath 数学函数" },
  { label: "log2", kind: "Function", detail: "cmath 数学函数" },
  { label: "log10", kind: "Function", detail: "cmath 数学函数" },
  { label: "exp", kind: "Function", detail: "cmath 数学函数" },
  { label: "sin", kind: "Function", detail: "cmath 数学函数" },
  { label: "cos", kind: "Function", detail: "cmath 数学函数" },
  { label: "tan", kind: "Function", detail: "cmath 数学函数" },
  { label: "atan2", kind: "Function", detail: "cmath 数学函数" },
  { label: "fabs", kind: "Function", detail: "cmath 浮点绝对值" },
];

// OI 常用宏常量 + 扩展类型
const OI_MACROS_AND_TYPES: KeywordDef[] = [
  { label: "INT_MAX", kind: "Constant", detail: "climits 宏常量" },
  { label: "INT_MIN", kind: "Constant", detail: "climits 宏常量" },
  { label: "LLONG_MAX", kind: "Constant", detail: "climits 宏常量" },
  { label: "LLONG_MIN", kind: "Constant", detail: "climits 宏常量" },
  { label: "UINT_MAX", kind: "Constant", detail: "climits 宏常量" },
  { label: "ULLONG_MAX", kind: "Constant", detail: "climits 宏常量" },
  { label: "INFINITY", kind: "Constant", detail: "cmath 浮点无穷" },
  { label: "NAN", kind: "Constant", detail: "cmath 浮点 NaN" },
  { label: "EOF", kind: "Constant", detail: "cstdio 文件结束符" },
  { label: "NULL", kind: "Constant", detail: "cstddef 空指针" },
  { label: "CHAR_BIT", kind: "Constant", detail: "climits 字节位数" },
  { label: "int8_t", kind: "Class", detail: "标准定宽整数类型" },
  { label: "uint8_t", kind: "Class", detail: "标准定宽整数类型" },
  { label: "int16_t", kind: "Class", detail: "标准定宽整数类型" },
  { label: "uint16_t", kind: "Class", detail: "标准定宽整数类型" },
  { label: "__int128_t", kind: "Class", detail: "GCC 扩展 128 位整数" },
  { label: "__uint128_t", kind: "Class", detail: "GCC 扩展 128 位无符号整数" },
];

export const CPP_KEYWORDS_ALL: KeywordDef[] = [
  ...CPP_KEYWORDS,
  ...STL_CONTAINERS,
  ...STL_ALGORITHMS,
  ...OI_ALGORITHMS_EXT,
  ...CPP_IO_TYPES,
  ...OI_MACROS_AND_TYPES,
  ...CPP_HEADERS,
  ...CPP_PREPROCESSOR,
];
